#pragma once

#include <string>
#include <iostream>
#include <vector>
#include "FileSystem/FileSystem.h"

#include <includedLibraries/stb_image.h>
#include <bgfx/bgfx.h>

#include "malloc_override.h"
#include "Helpers/StringHelper.h"
#include <Profiling/ResourceStatistics.hpp>
#include <cstring> // for memcpy

class CubemapTexture
{
public:
    // faces should be provided in this order:
    // right(+X), left(-X), top(+Y), bottom(-Y), front(+Z), back(-Z)
    CubemapTexture(const std::vector<std::string>& faces, bool generateMipmaps = false) {
        if (faces.size() != 6) {
            std::cerr << "Cubemap texture requires exactly 6 faces." << std::endl;
            return;
        }
        loadFromFiles(faces, generateMipmaps);
    }

    CubemapTexture(const std::string& base, bool generateMipmaps = false) {
        std::vector<std::string> faces;

        faces.push_back(StringHelper::Replace(base, ".", "_lf."));
        faces.push_back(StringHelper::Replace(base, ".", "_rt."));
        faces.push_back(StringHelper::Replace(base, ".", "_up."));
        faces.push_back(StringHelper::Replace(base, ".", "_dn."));
        faces.push_back(StringHelper::Replace(base, ".", "_ft."));
        faces.push_back(StringHelper::Replace(base, ".", "_bk."));

        loadFromFiles(faces, false);
    }

    ~CubemapTexture() {
        ResourceStatistics::Instance().unregisterResource(ResourceType::TextureCube, m_handle.idx);

        if (bgfx::isValid(m_handle))
            bgfx::destroy(m_handle);
    }

    void bind(uint8_t stage, bgfx::UniformHandle sampler) const {
        bgfx::setTexture(stage, sampler, m_handle);
    }

    bool valid = false;

    bgfx::TextureHandle getHandle() const {
        return m_handle;
    }

    // Backward-compat: return numeric ID for ResourceStatistics etc.
    uint16_t getID() const {
        return m_handle.idx;
    }

    bgfx::TextureHandle getTextureHandle() const {
        return m_handle;
    }

    void setName(const std::string& name) {
        ResourceStatistics::Instance().setResourceName(ResourceType::TextureCube, m_handle.idx, name);
        if (bgfx::isValid(m_handle))
            bgfx::setName(m_handle, name.c_str(), (int32_t)name.size());
    }

private:
    bgfx::TextureHandle m_handle = BGFX_INVALID_HANDLE;

    // -----------------------------------------------------------------------
    // Helper: rotate an SDL_Surface 90° CW or CCW (kept for orientation compatibility)
    // Allocates and returns a new RGBA buffer rotated 90° CW (cw=true) or CCW.
    // Caller must free with stbi_image_free().
    // -----------------------------------------------------------------------
    static stbi_uc* rotate90_rgba(const stbi_uc* src, int w, int h, bool cw)
    {
        stbi_uc* dst = static_cast<stbi_uc*>(malloc(w * h * 4));
        if (!dst) return nullptr;

        for (int y = 0; y < h; ++y)
        {
            for (int x = 0; x < w; ++x)
            {
                const stbi_uc* s = src + (y * w + x) * 4;
                stbi_uc* d;
                if (cw)
                    d = dst + (x * h + (h - 1 - y)) * 4; // CW:  dst(x, h-1-y)
                else
                    d = dst + ((w - 1 - x) * h + y) * 4; // CCW: dst(w-1-x, y)
                d[0] = s[0]; d[1] = s[1]; d[2] = s[2]; d[3] = s[3];
            }
        }
        return dst;
    }

    // -----------------------------------------------------------------------
    // Flags (identical to Texture.hpp)
    // -----------------------------------------------------------------------
    static uint64_t buildFlags(bool generateMipmaps) {
        uint64_t flags = BGFX_TEXTURE_NONE
            | BGFX_SAMPLER_MIN_ANISOTROPIC
            | BGFX_SAMPLER_MAG_ANISOTROPIC;

        if (!generateMipmaps)
            flags |= BGFX_TEXTURE_NONE; // mipmaps are auto-generated by bgfx when data is provided

        return flags;
    }

    // -----------------------------------------------------------------------
    // Load (all faces → single contiguous memory block for bgfx::createTextureCube)
    // -----------------------------------------------------------------------
    void loadFromFiles(const std::vector<std::string>& faces, bool generateMipmaps)
    {
        if (faces.size() != 6) {
            std::cerr << "[Cubemap] Need 6 faces, got " << faces.size() << std::endl;
            return;
        }

        uint16_t faceSize = 0;
        int commonWidth = 0;
        int commonHeight = 0;
        size_t totalBaseSize = 0;
        std::vector<stbi_uc*> loadedPixels(6, nullptr);
        bool loadSuccess = true;

        for (unsigned i = 0; i < 6; ++i)
        {
            std::vector<uint8_t> fileData = FileSystemEngine::ReadFileBinary(faces[i]);
            if (fileData.empty()) {
                std::cerr << "[Cubemap] File empty or not found: " << faces[i] << "\n";
                loadSuccess = false;
                continue;
            }

            int width = 0, height = 0, channels = 0;
            stbi_uc* pixels = stbi_load_from_memory(
                fileData.data(),
                static_cast<int>(fileData.size()),
                &width, &height, &channels,
                STBI_rgb_alpha
            );

            if (!pixels) {
                std::cerr << "[Cubemap] stbi_load_from_memory failed for "
                    << faces[i] << ": " << stbi_failure_reason() << std::endl;
                loadSuccess = false;
                continue;
            }

            // rotate +Y (index 2) 90° CW, –Y (index 3) 90° CCW (exact same as original)
            if (i == 2 || i == 3) {
                bool cw = (i == 2);
                stbi_uc* rotated = rotate90_rgba(pixels, width, height, cw);
                stbi_image_free(pixels);
                if (!rotated) {
                    std::cerr << "[Cubemap] Rotation failed for "
                        << faces[i] << std::endl;
                    loadSuccess = false;
                    continue;
                }
                pixels = rotated;
                std::swap(width, height);
            }

            loadedPixels[i] = pixels;

            // dimensions from first face + consistency check
            if (i == 0) {
                commonWidth = width;
                commonHeight = height;
                faceSize = (uint16_t)width;
            }
            else if (width != commonWidth || height != commonHeight) {
                std::cerr << "[Cubemap] Face " << i << " size mismatch after processing: "
                    << width << "x" << height << " vs " << commonWidth << "x" << commonHeight << std::endl;
                loadSuccess = false;
            }

            const size_t faceBytes = static_cast<size_t>(width) * height * 4;
            totalBaseSize += faceBytes;
        }

        if (!loadSuccess || faceSize == 0) {
            for (auto p : loadedPixels) if (p) stbi_image_free(p);
            return;
        }

        // Build single contiguous RGBA8 buffer (6 faces in bgfx order)
        const size_t faceBytes = static_cast<size_t>(commonWidth) * commonHeight * 4;
        totalBaseSize = faceBytes * 6;
        std::vector<unsigned char> allData(totalBaseSize);

        size_t offset = 0;
        for (unsigned i = 0; i < 6; ++i) {
            if (loadedPixels[i]) {
                memcpy(&allData[offset], loadedPixels[i], faceBytes);
                stbi_image_free(loadedPixels[i]);
                offset += faceBytes;
            }
            else {
                memset(&allData[offset], 0, faceBytes);
                offset += faceBytes;
            }
        }

        const bgfx::Memory* mem = bgfx::copy(allData.data(), (uint32_t)totalBaseSize);

        uint64_t flags = buildFlags(generateMipmaps);

        m_handle = bgfx::createTextureCube(
            faceSize,               // side length (square faces)
            generateMipmaps,        // hasMips – bgfx auto-generates mipmaps if true
            1,                      // numLayers (regular cubemap)
            bgfx::TextureFormat::RGBA8,
            flags,
            mem
        );

        if (!bgfx::isValid(m_handle)) {
            std::cerr << "bgfx::createTextureCube failed (" << faceSize << ")\n";
            return;
        }

        // Resource statistics (identical logic to Texture.hpp)
        size_t textureSize = totalBaseSize;
        if (generateMipmaps)
            textureSize += totalBaseSize / 3;

        // Common prefix for resource name (exact same as original)
        std::string resourceName = "Cubemap";
        if (!faces.empty()) {
            resourceName = faces[0];
            for (size_t i = 1; i < faces.size(); ++i) {
                size_t minLen = std::min(resourceName.length(), faces[i].length());
                size_t j = 0;
                while (j < minLen && resourceName[j] == faces[i][j])
                    ++j;
                resourceName = resourceName.substr(0, j);
            }
            if (resourceName.empty() || resourceName.length() < 3)
                resourceName = "Cubemap";
        }

        ResourceStatistics::Instance().registerResource(
            ResourceType::TextureCube,
            m_handle.idx,
            textureSize,
            resourceName
        );

        bgfx::setName(m_handle, resourceName.c_str(), (int32_t)resourceName.size());

        valid = true;
    }
};