#pragma once

#include <string>
#include <iostream>
#include <vector>
#include "FileSystem/FileSystem.h"

#include <includedLibraries/stb_image.h>
#include <bgfx/bgfx.h>

#include "malloc_override.h"
#include "Logger.hpp"
#include <Profiling/ResourceStatistics.hpp>

class Texture {
public:
    Texture(const std::string& filename, bool generateMipmaps = true) {
        loadFromFile(filename, generateMipmaps);
    }

    Texture() {}

    // Load from compressed data (PNG/JPEG in memory)
    Texture(const unsigned char* data, size_t size, bool generateMipmaps = true) {
        loadFromMemoryCompressed(data, size, generateMipmaps);
    }

    // Load from raw pixel data (RGBA or BGRA)
    Texture(const unsigned char* data, int width, int height, bgfx::TextureFormat::Enum format = bgfx::TextureFormat::RGBA8, bool generateMipmaps = true) {
        loadFromRawData(data, width, height, format, generateMipmaps);
    }

    ~Texture() {
        ResourceStatistics::Instance().unregisterResource(ResourceType::Texture, m_handle.idx);

        if (bgfx::isValid(m_handle))
            bgfx::destroy(m_handle);
    }

    void bind(uint8_t stage, bgfx::UniformHandle sampler) const {
        bgfx::setTexture(stage, sampler, m_handle);
    }

    bool valid = false;

    bgfx::TextureHandle getHandle() const {
        return m_handle;
    }

    // Backward-compat: return numeric ID for ResourceStatistics etc.
    uint16_t getID() const {
        return m_handle.idx;
    }

    bgfx::TextureHandle getTextureHandle() const {
        return m_handle;
	}

    void setName(const std::string& name) {
        ResourceStatistics::Instance().setResourceName(ResourceType::Texture, m_handle.idx, name);
        if (bgfx::isValid(m_handle))
            bgfx::setName(m_handle, name.c_str(), (int32_t)name.size());
    }

private:
    bgfx::TextureHandle m_handle = BGFX_INVALID_HANDLE;

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    static uint64_t buildFlags(bool generateMipmaps) {
        uint64_t flags = BGFX_TEXTURE_NONE
            | BGFX_SAMPLER_MIN_ANISOTROPIC
            | BGFX_SAMPLER_MAG_ANISOTROPIC;

        if (!generateMipmaps)
            flags |= BGFX_TEXTURE_NONE; // mipmaps are auto-generated by bgfx when data is provided

        return flags;
    }

    static size_t bytesPerPixel(bgfx::TextureFormat::Enum fmt) {
        switch (fmt) {
        case bgfx::TextureFormat::R8:       return 1;
        case bgfx::TextureFormat::RG8:      return 2;
        case bgfx::TextureFormat::RGB8:     return 3;
        case bgfx::TextureFormat::RGBA8:    return 4;
        case bgfx::TextureFormat::BGRA8:    return 4;
        default:                            return 4;
        }
    }

    static std::string formatSuffix(bgfx::TextureFormat::Enum fmt) {
        switch (fmt) {
        case bgfx::TextureFormat::R8:    return "_R";
        case bgfx::TextureFormat::RG8:   return "_RG";
        case bgfx::TextureFormat::RGB8:  return "_RGB";
        case bgfx::TextureFormat::RGBA8: return "_RGBA";
        case bgfx::TextureFormat::BGRA8: return "_BGRA";
        default:                         return "_Unknown";
        }
    }

    // -----------------------------------------------------------------------
    // Core upload
    // -----------------------------------------------------------------------
    void setupTexture(int width, int height,
        bgfx::TextureFormat::Enum format,
        const void* pixels,
        bool generateMipmaps)
    {
        if (width <= 0 || height <= 0 || !pixels) return;

        const uint32_t dataSize = (uint32_t)(width * height * bytesPerPixel(format));
        const bgfx::Memory* mem = bgfx::copy(pixels, dataSize);

        uint64_t flags = buildFlags(generateMipmaps);

        // hasMips=false: bgfx generates them internally when the flag is set.
        // Pass hasMips=false, numLayers=1; bgfx handles mip chain automatically.
        m_handle = bgfx::createTexture2D(
            (uint16_t)width,
            (uint16_t)height,
            generateMipmaps,   // hasMips – tells bgfx to expect/generate mip chain
            1,                 // numLayers
            format,
            flags,
            mem
        );

        if (!bgfx::isValid(m_handle)) {
            std::cerr << "bgfx::createTexture2D failed (" << width << "x" << height << ")\n";
            return;
        }

        // Resource statistics
        size_t textureSize = dataSize;
        if (generateMipmaps)
            textureSize += textureSize / 3;

        std::string textureName = "Texture_"
            + std::to_string(width) + "x" + std::to_string(height)
            + formatSuffix(format)
            + (generateMipmaps ? "_Mips" : "");

        ResourceStatistics::Instance().registerResource(
            ResourceType::Texture,
            m_handle.idx,
            textureSize,
            textureName
        );

        valid = true;
    }

    // -----------------------------------------------------------------------
    // Load paths
    // -----------------------------------------------------------------------
    void loadFromFile(const std::string& filename, bool generateMipmaps) {
        std::vector<uint8_t> fileData = FileSystemEngine::ReadFileBinary(filename);
        if (fileData.empty()) {
            std::cerr << "File empty or not found: " << filename << "\n";
            return;
        }

        loadFromMemoryCompressed(fileData.data(), fileData.size(), generateMipmaps);

        if (bgfx::isValid(m_handle)) {
            bgfx::setName(m_handle, filename.c_str(), (int32_t)filename.size());
            ResourceStatistics::Instance().setResourceName(ResourceType::Texture, m_handle.idx, filename);
        }
    }

    void loadFromMemoryCompressed(const unsigned char* data, size_t size, bool generateMipmaps) {
        int width, height, channels;
        // Force RGBA8 — universally supported by bgfx across all backends
        unsigned char* pixels = stbi_load_from_memory(
            data, (int)size, &width, &height, &channels, 4);

        if (!pixels) {
            std::cerr << "stbi_load_from_memory failed: " << stbi_failure_reason() << "\n";
            return;
        }

        setupTexture(width, height, bgfx::TextureFormat::RGBA8, pixels, generateMipmaps);
        stbi_image_free(pixels);
    }

    void loadFromRawData(const unsigned char* data, int width, int height,
        bgfx::TextureFormat::Enum format, bool generateMipmaps)
    {
        if (!data) {
            std::cerr << "loadFromRawData: null data pointer\n";
            return;
        }
        setupTexture(width, height, format, data, generateMipmaps);
    }
};