# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.31)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS OpenAL::OpenAL)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target OpenAL::OpenAL
add_library(OpenAL::OpenAL STATIC IMPORTED)

set_target_properties(OpenAL::OpenAL PROPERTIES
  CXX_MODULE_STD ""
  IMPORTED_CXX_MODULES_COMPILE_DEFINITIONS "AL_LIBTYPE_STATIC;AL_BUILD_LIBRARY;AL_ALEXT_PROTOTYPES;ALC_API=;AL_API=;_WIN32;NOMINMAX;WIN32_LEAN_AND_MEAN;_CRT_SECURE_NO_WARNINGS;_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR;NDEBUG;_MSVC_STL_HARDENING=1"
  IMPORTED_CXX_MODULES_COMPILE_OPTIONS "/O2;/Zi;/FS;/EHsc;/MP;\$<\$<COMPILE_LANGUAGE:CXX>:/permissive->;/W4;/wd4127;/wd4324;/wd4373;/utf-8;\$<\$<COMPILE_LANGUAGE:CXX>:/EHsc>"
  IMPORTED_CXX_MODULES_INCLUDE_DIRECTORIES "F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft;F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include;F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/gsl/include;F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include;F:/Git/SdlWasmEngine/BuildWindows/sourceLibraries/openAlSoft;F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft;F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/common"
  IMPORTED_CXX_MODULES_LINK_LIBRARIES "Threads::Threads;avrt;winmm"
  INTERFACE_COMPILE_DEFINITIONS "AL_LIBTYPE_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include;F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include;F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include/AL"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:Threads::Threads>;\$<LINK_ONLY:avrt>;\$<LINK_ONLY:winmm>;\$<LINK_ONLY:>"
)

if(NOT CMAKE_VERSION VERSION_LESS "3.23.0")
  target_sources(OpenAL::OpenAL
    INTERFACE
      FILE_SET "public_headers"
      TYPE "HEADERS"
      BASE_DIRS "F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include"
      FILES "F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include/AL/al.h" "F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include/AL/alc.h" "F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include/AL/alext.h" "F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include/AL/efx.h" "F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include/AL/efx-presets.h"
  )
else()
  set_property(TARGET OpenAL::OpenAL
    APPEND PROPERTY INTERFACE_INCLUDE_DIRECTORIES
      "F:/Git/SdlWasmEngine/sourceLibraries/openAlSoft/include"
  )
endif()

# Import target "OpenAL::OpenAL" for configuration "Release"
set_property(TARGET OpenAL::OpenAL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(OpenAL::OpenAL PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LOCATION_RELEASE "F:/Git/SdlWasmEngine/BuildWindows/sourceLibraries/openAlSoft/OpenAL32.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
